version: '3.9'
services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./docs:/var/www/html
    ports:
      - 80:8080

  agate:
    image: ghcr.io/yude/agate-docker:main
    restart: always
    environment:
      - AGATE_HOST=g.yude.jp
    volumes:
      - ./docs:/app/content
      - ./certs:/app/certs
    ports:
      - 1965:1965
