version: '3.9'
services:
  nginx:
    image: nginx:latest
    restart: always
    user: root
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./docs:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 81:81
      - 443:443

  agate:
    image: ghcr.io/yude/agate-docker:main
    restart: always
    environment:
      - AGATE_HOST=yude.jp
    volumes:
      - ./docs:/app/content
      - ./certs:/app/certs
    ports:
      - 1965:1965
